name: Deploy to Staging

on:
  push:
    branches:
      - main # Le workflow se déclenche uniquement sur la branche "staging"

jobs:
  deploy-staging:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Vérifier le dépôt
    - name: Checkout repository
      uses: actions/checkout@v3

    # Étape 2 : Configurer la clé SSH pour la connexion au serveur
    - name: Set up SSH
      run: |
        echo "${{ secrets.STAGING_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.STAGING_HOST }} >> ~/.ssh/known_hosts

    # Étape 3 : Copier les fichiers sur le serveur avec SCP
    - name: Deploy files to Staging
      env:
        STAGING_HOST: ${{ secrets.STAGING_HOST }}
        STAGING_USER: ${{ secrets.STAGING_USER }}
      run: |
        scp -r ./ "${STAGING_USER}@${STAGING_HOST}:/var/www/staging"

    # Étape 4 : Notifier que le déploiement est terminé
    - name: Notify Deployment Success
      if: success()
      run: echo "Deployment to staging completed successfully!"
