name: Portfolio

on:
  push:
    branches:
      - main

jobs:
  test-deployment:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Global Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y npm

      - name: Install Project Dependencies
        working-directory: ./Projet
        run: |
          npm install

      - name: Run Tests
        working-directory: ./Projet
        run: |
          npx vitest run || true

  linting-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ESLint
        working-directory: ./Projet
        run: |
          npm install eslint --save-dev

      - name: Lint JavaScript Files
        working-directory: ./Projet
        run: |
          npx eslint scripts/*.js || true
